### PR TITLE
Create All Fide Chess Analysis

### PR DESCRIPTION
**Pull request by guptavaibhav159**
Please Add Hacktoberfest Accepted Tag/Label To it.

### CODE REVIEW

**Comment by mbiesiad** [comment]
Wow, looks impressive! I will make a CR soon.

Sure, no problem. Great work! Keep in touch :octocat:

**Comment by guptavaibhav159** [comment]
Could You please Add Hacktoberfest Accepted Label to It. You may take your time to merge it.

**Comment by mbiesiad** [comment]
Good point. Done 🚀

**Review by mbiesiad — APPROVED** [review]

**Comment by mbiesiad** [comment]
One must live long to learn! Awesome solution with {[%clk h:m:s]} 

Merged 🔥 Thanks a lot again, great job! :tada: Best wishes,

**Pull request merged**
